doctrine:
    dbal:
        url: mysql://minutee01:Aqw78929@minutee01.mysql.db:3306/minutee01 
        #mysql://root:@127.0.0.1:3306/boxracingv2?serverVersion=mariadb-10.4.11 
        #'%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
