easy_admin:
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        Category:
            class: App\Entity\Category
            label: 'Catégories (menu du site)'
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'Name', label: 'Nom de la catégorie'}
                    - { property: 'IsActive', label: 'Catégorie active (oui/non)'}

        Announcement:
            class: App\Entity\Announcement
            label: 'Annonces'
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'Title', label: 'Titre'}
                    - { property: 'Description', label: 'Description'}
                    - { property: 'DatePublish', label: 'Date de publication'}
                    - { property: 'IsActive', label: 'Rendre visible sur le site'}
                    - { property: 'Price', label: 'Prix'}
                    - { property: 'Image', label: 'Image annonce'}
                    - { property: 'Category', label: 'Catégorie du service'}
                    - { property: 'User', label: 'Emmetteur'}

        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'FirstName', label: 'Prénom'}
                    - { property: 'LastName', label: 'Nom'}
                    - { property: 'Phone', label: 'Téléphone'}
                    - { property: 'Email', label: 'E-mail'}
                    - { property: 'Address', label: 'Adresse'}
                    - { property: 'CodePoste', label: 'Code postale'}
                    - { property: 'City', label: 'Ville'}
                    - { property: 'IsActive', label: 'Utilisateur actif'}
                    - { property: 'IsPro', label: 'Est pro'}

        Sale:
            class: App\Entity\Sale
            label: 'Ventes'
            form:
                fields:
                    - { property: 'Command', label: 'Commande', type_options: { disabled: true }}
                    - { property: 'IdAnnouncement', label: 'Id Annonce', type_options: { disabled: true }}
                    - { property: 'SellerName', label: 'Vendeur', type_options: { disabled: true }}
                    - { property: 'IdSeller', label: 'Identifiant Vendeur', type_options: { disabled: true }}
                    - { property: 'BuyerName', label: 'Acheteur', type_options: { disabled: true }}
                    - { property: 'IdBuyer', label: 'Identifiant Acheteur', type_options: { disabled: true }}
                    - { property: 'DateofSale', label: 'Date de la vente', type_options: { disabled: true }}
                    - { property: 'Price', label: 'Montant de la commande', type_options: { disabled: true }}
                    - { property: 'Cgv', label: 'Acceptation des conditions générales de ventes', type_options: { disabled: true }}
                    - { property: 'State', label: 'Status', type_options: { disabled: true }}

        ImageCategory:
            class: App\Entity\ImageCategory
            label: 'Images Catégories'
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    #- { property: 'virtualFilename', type: 'file_upload', type_options: {upload_dir: 'templates/imagescat',upload_filename: '[uuid].[extension]' }}
                    - { property: 'Path', type: 'file_upload', type_options: { upload_dir: 'templates/imagescat/' } }
                    - 'Category'

        Payment:
            class: App\Entity\Payment
            label: 'Paramétrage paybox'
            form:
                fields:
                    - { property: 'pbx_site', label: 'Site'}
                    - { property: 'pbx_rang', label: 'Rang'}
                    - { property: 'pbx_identifiant', label: 'Identifant'}
                    - { property: 'pbx_devise', label: 'Devise utilisée (€)'}
                    - { property: 'pbx_hash', label: 'HASH'}
                    - { property: 'pbx_effectue', label: 'URL page accepte paiement'}
                    - { property: 'pbx_annule', label: 'URL page annuler paiement'}
                    - { property: 'pbx_refuse', label: 'URL page refus paiement'}
                    - { property: 'pbx_repondre_a', label: 'URL backoffice'}
                    - { property: 'pbx_retour', label: 'Clef retour'}
                    - { property: 'HMAC', label: 'Clef HMAC'}
                    - { property: 'serveur_primaire', label: 'Serveur primaire'}
                    - { property: 'serveur_secondaire', label: 'Serveur Secondaire'}

        Email:
            class: App\Entity\Email
            label: 'Emails automatique'
            form:
                fields:
                    - { property: 'KeyEmail', label: 'Clef du mail'}
                    - { property: 'EmailAddress', label: 'E-mail adresse'}
                    - { property: 'Object', label: 'Objet du mail'}
                    - { property: 'Message', type: 'fos_ckeditor', label: 'Contenu du mail'}

        Bank:
            class: App\Entity\Bank
            label: 'RIB des vendeurs'
            form:
                fields:
                    - { property: 'Iban', label: 'IBAN vendeur'}
                    - { property: 'Bic', label: 'Bic vendeur'}
                    - { property: 'User', label: 'Utilisateur'}

        Code:
            class: App\Entity\Code
            label: 'Code validation commande'
            form:
                fields:
                    - { property: 'Code', label: 'Code De Validation',type_options: { disabled: true }}
                    - { property: 'Command', label: 'Commande',type_options: { disabled: true }}
                    - { property: 'DateStart', type: datetime, label: 'Date Début Validité',type_options: { disabled: true }}
                    - { property: 'DateEnd',type: datetime, label: 'Date Fin Validité',type_options: { disabled: true }}