easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            label: 'Catégories'
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - 'Name'
                    - 'IsActive'

        Announcement:
            class: App\Entity\Announcement
            label: 'Annonces'
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - 'Title'
                    - 'Description'
                    - 'DatePublish'
                    - 'IsActive'
                    - 'Price'
                    - 'Image'
                    - 'Category'
