swiftmailer:
    transport: sendmail
    username: infocontact@1minutepresta.fr
    password: 'Aqw789292919@29'
    auth_mode: login
    disable_delivery: false
    encryption: ssl
    port: 465
    host: ssl0.ovh.net
