index:
    path: /
    controller: App\Controller\IndexController::index
category:
    path: /category/{id}
    controller: App\Controller\CategoryController::category
announcement:
    path: /announcement/{id}
    controller: App\Controller\DetailAnnouncenementController::announcement
account:
    path: /account
    controller: App\Controller\AccountController::account
createuser:
    path: /createuser
    controller: App\Controller\AccountController::create
login:
    path: /login
    controller: App\Controller\LoginController::login
logout:
    path: /logout
    controller: App\Controller\LoginController::logout
deleteAnnouncement:
    path: /account/delete/{id}
    controller: App\Controller\AccountController::delete
createAccount:
    path: /accountcreate
    controller: App\Controller\AccountController::createAccount
createannouncementview:
    path: /account/create/announcement
    controller: App\Controller\AnnouncementController::createView
createannouncement:
    path: /createannouncement
    controller: App\Controller\AnnouncementController::create
contact:
    path: /contact
    controller: App\Controller\ContactController::contact
sendmail:
    path: /sendmail
    controller: App\Controller\ContactController::sendMail
declaration:
    path: /declaration
    controller: App\Controller\TaxDeclarationController::declaration