index:
    path: /
    controller: App\Controller\IndexController::index
category:
    path: /category/{id}
    controller: App\Controller\CategoryController::category
announcement:
    path: /announcement/{id}
    controller: App\Controller\DetailAnnouncenementController::announcement
account:
    path: /account
    controller: App\Controller\AccountController::account
login:
    path: /login
    controller: App\Controller\LoginController::login
logout:
    path: /logout
    controller: App\Controller\LoginController::logout
deleteAnnouncement:
    path: /account/delete/{id}
    controller: App\Controller\AccountController::delete