index:
    path: /
    controller: App\Controller\IndexController::index
category:
    path: /category/{id}
    controller: App\Controller\CategoryController::category
announcement:
    path: /announcement/{id}
    controller: App\Controller\DetailAnnouncenementController::announcement
account:
    path: /account
    controller: App\Controller\AccountController::account
createuser:
    path: /createuser
    controller: App\Controller\AccountController::create
login:
    path: /login
    controller: App\Controller\LoginController::login
logout:
    path: /logout
    controller: App\Controller\LoginController::logout
deleteAnnouncement:
    path: /account/delete/{id}
    controller: App\Controller\AccountController::delete
createAccount:
    path: /accountcreate
    controller: App\Controller\AccountController::createAccount
createannouncementview:
    path: /account/create/announcement
    controller: App\Controller\AnnouncementController::createView
createannouncement:
    path: /createannouncement
    controller: App\Controller\AnnouncementController::create
contact:
    path: /contact
    controller: App\Controller\ContactController::contact
sendmail:
    path: /sendmail
    controller: App\Controller\ContactController::sendMail
declaration:
    path: /declaration
    controller: App\Controller\TaxDeclarationController::declaration
payment:
    path: /payment/{id}
    controller: App\Controller\PaymentController::payment
cart:
    path: /cart/{id}
    controller: App\Controller\PaymentController::cart
confirmation:
    path: /confirmation
    controller: App\Controller\PaymentController::confirmation
createribview:
    path: /account/create/rib
    controller: App\Controller\RibController::createView
createrib:
    path: /createrib
    controller: App\Controller\RibController::create
editaccount:
    path: /accountedit
    controller: App\Controller\AccountController::editAccountView
edituser:
    path: /edituser
    controller: App\Controller\AccountController::editUser
editbankview:
    path: /editbankview/{id}
    controller: App\Controller\RibController::editBankView
editbank:
    path: /editbank
    controller: App\Controller\RibController::editBank
editannoucementview:
    path: /editannoucementview/{id}
    controller: App\Controller\AnnouncementController::editAnnoucementView
editannouncement:
    path: /editannouncement
    controller: App\Controller\AnnouncementController::editAnnouncement
codepayment:
    path: /code/{command}/{idUser}
    controller: App\Controller\CodeController::code
codesend:
    path: /codesend
    controller: App\Controller\CodeController::sendCode
codeconfirmation:
    path: /codeconfirmation
    controller: App\Controller\CodeController::codeConfirmation
offer:
    path: /offer
    controller: App\Controller\OfferController::offerList